services:
  _base:
    image: saleel/circom:2.1.6
    volumes:
      - type: bind
        source: ./mycircuits
        target: /mycircuits

  terminal:
    depends_on: _base
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
