name: 'Pandoc MD to HTML'
description: 'Compiles markdown to html with pandoc'

inputs:
  source:
    required: true
    type: string
  target:
    required: true
    type: string
  title:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - uses: docker://pandoc/core:3.5
      with:
        args: >- # allows you to break string into multiple lines
          --include-in-header=./styling.css
          -s
          -f
          markdown+smart
          --metadata
          "pagetitle=${{inputs.title}}"
          --to=html5
          ${{inputs.source}}
          -o ${{inputs.target}}
