name: Export Exercise Material Part 2
on:
  workflow_call:

jobs:
  export-exercise-material-part-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # required for accessing files in repository.
      
      - name: Create Folder Structure
        run: |
          mkdir snarkjs_part_2
          mkdir snarkjs_part_2/mycircuits
          mkdir snarkjs_part_2/mycircuits_solutions
      
      - name: Compile Readme (Pandoc)
        uses: ./.github/actions/pandoc-md-to-html
        with:
          title: "SnarkJS Part II"
          source: readmes/README_2.md
          target: snarkjs_part_2/README.html

      - name: Copying files to folder
        run: cp -r mycircuits/circomlib ./snarkjs_part_2/mycircuits

      - name: Parsing Circom Files, Assignments
        run: |
          cat ./mycircuits/mastermind.circom | ./solution_parser.py exercises > ./snarkjs_part_2/mycircuits/mastermind.circom

      - name: Parsing Circom Files, Solutions
        run: |
          cat ./mycircuits/mastermind.circom | ./solution_parser.py solutions iterative > ./snarkjs_part_2/mycircuits_solutions/mastermind_solutions_iterative.circom
          cat ./mycircuits/mastermind.circom | ./solution_parser.py solutions recursive > ./snarkjs_part_2/mycircuits_solutions/mastermind_solutions_recursive.circom

      - name: Zipping
        run: zip -r snarkjs_part_2.zip ./snarkjs_part_2/ 

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snarkjs_part_2.zip
          path: snarkjs_part_2.zip
