name: Export Exercise Material
run-name: ${{ github.actor }} is exporting SnarkJS exercises 🚀
on:
  workflow_dispatch:
  push:
     branches:
       - main

jobs:
  export-exercise-material-part-1:
    uses: ./.github/workflows/export_exercise_material_part_1.yml

  export-exercise-material-part-2:
    uses: ./.github/workflows/export_exercise_material_part_2.yml
